# ownCloud with MariaDB/MySQL
#
# Access via "http://localhost:8080" (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# During initial ownCloud setup, select "Storage & database" --> "Configure the database" --> "MySQL/MariaDB"
# Database user: root
# Database password: owncloud
# Database name: owncloud
# Database host: replace "localhost" with "mysql"

version: '3'

services:

  owncloud:
    image: owncloud
    ports:
      - 8081:80

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: owncloud
      