# Creator: Eddy Elbrink
# Project: Inethi Network
# Container: ownCloud with MariaDB/MySQL
#
# ownCloud URL = "http://localhost:8081"
#
# Initial ownCloud setup, select "Storage & database" --> "Configure the database" --> "MySQL/MariaDB"
# Database user: root
# Database password: owncloud
# Database name: owncloud
# Database host: replace "localhost" with "mysql"

version: '3'

services:

  owncloud:
    image: owncloud
    ports:
      - 8081:80
    depends_on:
      - mysql
    restart_policy:
    	condition: on-failure

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: owncloud
    restart_policy:
      condition: on-failure
      