# Creator: Eddy Elbrink
# Project: Inethi Network
# Service: Rocket.Chat
# Requirements: Rocket.Chat with MongoDB
#
# Access via "http://localhost:8082" (or "http://$(docker-machine ip):8082" if using docker-machine)
#

version: '3'

services:

  rocketchat:
    image: rocket.chat
    container_name: rocketchat-server
    ports:
      - 8082:80
    depends_on:
      - mongo
      
  mongo:
    image: mongo
    container_name: rocketchat-mongo
    environment:
      ROOT_URL: http://localhost